services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: life-insurance-app
    restart: always
    ports:
      - '${APP_PORT:-3000}:3000'
    env_file:
      - .env.app
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    external: true
